[tool.poetry]
name = "todo-ai"
version = "0.1.0"
description = ""
authors = ["Dawid Bogdanski <dawid.bogdanski@o2.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
